[package]
name = "pty-process"
version = "0.2.1"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2021"

description = "spawn commands attached to a pty"
repository = "https://git.tozt.net/pty-process"
readme = "README.md"
keywords = ["pty", "spawn", "execute", "process"]
categories = ["asynchronous", "command-line-interface"]
license = "MIT"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
libc = "0.2.119"
nix = "0.25"

tokio = { version = "1.17.0", features = ["fs", "process", "net"], optional = true }

[dev-dependencies]
futures = "0.3.21"
regex = "1.5.4"
term_size = "0.3.2"
tokio = { version = "1.21", features = ["full"] }

[features]
default = []

async = ["tokio"]
